controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# config/routes.yaml
api_login_check:
    path: /api/login_check
    controller: App\Controller\LoginController::login
    methods: [ POST ]